# Generated by Django 5.0.2 on 2024-02-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Game',
        ),
    ]
